version: '3.7'

services:
  rabbit-mq:
    image: rabbitmq:3.13.7-management
    container_name: rabbit-mq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - 'rabbit_data:/rabbit/data'
    networks:
      - quaoar-network

volumes:
  rabbit_data:

networks:
  quaoar-network:
    driver: bridge