# data source
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

messaging:
  active: ${ACTIVE_MESSAGING_SERVICE:RABBITMQ}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    virtual-host: ${RABBIT_MQ_VIRTUAL_HOST:quaoar}
    connection-timeout: ${RABBIT_MQ_CONNECTION_TIMEOUT:300000}
  aws:
    access: ${AWS_ACCESS_KEY:}
    secret: ${AWS_SECRET_KEY:}
    region: ${AWS_REGION:}
    ses:
      from: ${AWS_SES_FROM:}

broker:
  consumer:
    queues:
      delete-user: "delete-user.q"
      change-user: "change-user-info.q"
      subscribe-topic: "subscribe-to-topic.q"
      unsubscribe-topics: "unsubscribe-from-topics.q"
    routing-keys:
      delete-user: "delete-user"
      change-user: "change-user-info"
      subscribe-topic: "subscribe-to-topic"
      unsubscribe-topics: "unsubscribe-from-topics"
    exchange:
      name: "quaoar.topic"
    concurrent-consumers: 2
    prefetch-count: 15