server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  application:
    name: quaoar
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:db_quaoar}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3000
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: ProductionQuaoarPool
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health

messaging:
  active: ${ACTIVE_MESSAGING_SERVICE:}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    virtual-host: ${RABBIT_MQ_VIRTUAL_HOST:quaoar}
    connection-timeout: ${RABBIT_MQ_CONNECTION_TIMEOUT:300000}
  aws:
    access: ${AWS_ACCESS_KEY:123}
    secret: ${AWS_SECRET_KEY:123}
    region: ${AWS_REGION:us-east-1}
    ses:
      from: ${AWS_SES_FROM:example@example.com}

broker:
  consumer:
    queues:
      delete-user: "delete-user.q"
      change-user: "change-user-info.q"
      subscribe-topic: "subscribe-to-topic.q"
      unsubscribe-topics: "unsubscribe-from-topics.q"
    routing-keys:
      delete-user: "delete-user"
      change-user: "change-user-info"
      subscribe-topic: "subscribe-to-topic"
      unsubscribe-topics: "unsubscribe-from-topics"
    exchange:
      name: "quaoar.topic"
    concurrent-consumers: 1
    prefetch-count: 15