server:
  port: 8080

spring:
  application:
    name: quaoar
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:db_quaoar}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3000
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: ProductionQuaoar
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

broker:
  consumer:
    queues:
      delete-user: queue-delete-user
      change-user: queue-changer-user-info
      subscribe-topic: queue-subscribe-to-topic
      unsubscribe-topics: queue-unsubscribe-from-topics